### ISSUE TITLE
[DONE 1.1.3] Localization support

### ISSUE THREAD

**Issue by labpaw** [chylex/Better-Sprinting#3]
@chylex any chance to have localization support for MC 1.7.10? GUI and version checker messages should be localizable.

**Comment by chylex** [comment]
Possibly, I'll be looking into 1.8.8 update soon so I'll also release an update with localization. There won't be a separate website for it, so I'll just post an update in here and you can make a PR for the lang file.

**Comment by labpaw** [comment]
Cool, can you ping me before release so I can make translation for new release?

**Comment by chylex** [comment]
Yea.

**Comment by chylex** [comment]
Added localization support; there are some things I couldn't translate, like the kick messages, or update notifications which have data provided by the file server which can't handle any translations. I'm not sure what to do about that.

https://github.com/chylex/Better-Sprinting/blob/1.7.10/src/main/resources/assets/bettersprinting/lang/en_US.lang

**Comment by labpaw** [comment]
This is sad but ok. Can you also disable notifications about 1.8 version for 1.7.10 users? So, users on 1.7.10 will get notifications only about 1.7.10 updates and 1.8 users will get notifications only about 1.8 updates. Russian localization provided in PR.

**Comment by chylex** [comment]
Just removed them.

**Comment by chylex** [comment]
Alright, I think I managed to get the config comments and server side messages in there, they're still localized on client so it should be fine.

Messages for update notifications are not done, I think I will need to figure out a proper solution for HEE too because it's the only place with pluralization, and that's something I don't want to touch until I have a good way of handling it.

https://github.com/chylex/Better-Sprinting/blob/1.7.10/src/main/resources/assets/bettersprinting/lang/en_US.lang

(also updated ru_RU.lang to have updated comments, so if you haven't deleted the branch yet, pull the changes first; thanks)
