### ISSUE TITLE
Fly boost suggestions

### ISSUE THREAD

**Issue by ArtelGG** [chylex/Better-Sprinting#49]
**Potential new targets for #45:**
* [ ] Allow users to switch fly boost between hold/toggle modes.
* [ ] Allow fly boost to operate independently from the actual sprint toggle.

**Comment by chylex** [comment]
I don't want to use another keybind when sprint is already unused during flight, if that's what you mean by the second one.

Fly boost toggle used to work in previous versions, it doesn't work in 3.0.0 because of the complete overhaul of the controls system, but I agree it should be an option so I'll reintroduce it in the next update.

**Comment by ArtelGG** [comment]
By the second suggestion, I mean to separate the two, allowing fly boost to be toggled on/off independently from survival's sprint. (When using the sprint (toggle) bind*)

**EDIT:** What I meant was, allow fly boosting to have an option (or 3, I suppose) to toggle between hold/toggle/sprint binds. So, for example;
**Having it on hold:** hitting any one of the sprint binds, whether it be hold or toggle, will result in you having to hold the key down for you to receive the fly boost.
**Having it on toggle:** hitting any of the sprint binds, whether it be hold or toggle, will result in you toggling fly boost on/off.
**Having it on sprint binds:** will function as it does now, sprint (hold) will activate fly boost when it's held down, sprint (toggle) will toggle fly boost on press.
etc. etc.

**Comment by chylex** [comment]
Using toggle/hold in the "reversed way" doesn't make sense, I'd rather keep the meaning consistent.

Before your edit, I took it as a separate toggle state for sprinting and flying, so that you could for ex. keep flight toggled even if you switch into survival mode, which I think could be useful and will look into implementing anyways.

**Comment by chylex** [comment]
Closing in favor of https://github.com/chylex/Better-Controls, if this issue is still relevant for Better Controls feel free to reopen there.
