### ISSUE TITLE
[Request] Option to disable off toggling of the spinting key

### ISSUE THREAD

**Issue by Darkere** [chylex/Better-Sprinting#56]
Unfortunately, the mod does not allow for completely replicating the vanilla sprinting behavior. 

Without the mod installed pressing the sprint key will never cause you to stop sprinting. 
With the mod pressing the key while sprinting will cause the player to stop sprinting.

For a perfect player, this does not make a difference but I'm not quite perfect. Whenever I'm not sure whether or not I may have jumped a second too late (and will hit a wall before going up the block) I will start pressing the sprint button preemptively to be able to continue running afterward.

For this ( admittedly rather obscure) use case I would request an option to disable the ability to turn off sprinting with the keybind.

**Comment by chylex** [comment]
Unfortunately I found that implementing this option causes a few issues with other features, like toggle sprint, that rely on the sprint key behaving the way it is now.

In my testing, I found that if you tap the sprint key and hit a wall, the sprinting continues seamlessly, so the only issue is if you tap it and don't hit a wall. Would a possible compromise be to add a timer, so that sprinting only cancels if you tap and release the sprint key very quickly? That way you could hold it while climbing up a mountain, and it wouldn't reset if you don't end up slowing down at any point.

**Comment by chylex** [comment]
I believe https://github.com/chylex/Better-Controls has options to do what you wanted.
